// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteLevelReducer from "../complete_level_reducer";
import ImportCharacterReducer from "../import_character_reducer";
import ImportComponentReducer from "../import_component_reducer";
import ImportLevelReducer from "../import_level_reducer";
import ImportLootboxReducer from "../import_lootbox_reducer";
import ImportPieceReducer from "../import_piece_reducer";
import OpenLootboxReducer from "../open_lootbox_reducer";
import SelectCharacterReducer from "../select_character_reducer";

export type CompleteLevelParams = __Infer<typeof CompleteLevelReducer>;
export type ImportCharacterParams = __Infer<typeof ImportCharacterReducer>;
export type ImportComponentParams = __Infer<typeof ImportComponentReducer>;
export type ImportLevelParams = __Infer<typeof ImportLevelReducer>;
export type ImportLootboxParams = __Infer<typeof ImportLootboxReducer>;
export type ImportPieceParams = __Infer<typeof ImportPieceReducer>;
export type OpenLootboxParams = __Infer<typeof OpenLootboxReducer>;
export type SelectCharacterParams = __Infer<typeof SelectCharacterReducer>;

