// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Vec2,
  PlacementImportV1,
} from "./types";

export default {
  id: __t.uuid(),
  slug: __t.string(),
  name: __t.string(),
  isStarting: __t.bool(),
  active: __t.bool(),
  rewardLootboxId: __t.option(__t.uuid()),
  successors: __t.array(__t.uuid()),
  backdropSlug: __t.string(),
  get spawn() {
    return Vec2;
  },
  get finish() {
    return Vec2;
  },
  get placements() {
    return __t.array(PlacementImportV1);
  },
};
