// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.uuid(),
  name: __t.string(),
  style: __t.string(),
  rarityWeight: __t.u32(),
  density: __t.f32(),
  jumpSpeed: __t.f32(),
  flightTimeMs: __t.u32(),
  buoyancy: __t.f32(),
  fireResistance: __t.f32(),
  starter: __t.bool(),
};
