// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  LayerImport,
} from "./types";

export default {
  id: __t.string(),
  name: __t.string(),
  isStarting: __t.bool(),
  active: __t.bool(),
  rewardLootboxId: __t.string(),
  successors: __t.array(__t.string()),
  get layers() {
    return __t.array(LayerImport);
  },
};
