// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  levelId: __t.string().name("level_id"),
  z: __t.u8(),
  width: __t.u16(),
  height: __t.u16(),
  cellWidth: __t.u16().name("cell_width"),
  cellHeight: __t.u16().name("cell_height"),
  parallaxX: __t.f32().name("parallax_x"),
  parallaxY: __t.f32().name("parallax_y"),
  encoding: __t.string(),
  contentHash: __t.string().name("content_hash"),
  data: __t.byteArray(),
});
