// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BackdropLayerV1,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  slug: __t.string(),
  get sky() {
    return BackdropLayerV1;
  },
  get far() {
    return BackdropLayerV1;
  },
  get mid() {
    return BackdropLayerV1;
  },
});
