// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.uuid(),
  name: __t.string(),
  style: __t.string(),
  density: __t.f32(),
  jumpSpeed: __t.f32().name("jump_speed"),
  flightTimeMs: __t.u32().name("flight_time_ms"),
  buoyancy: __t.f32(),
  fireResistance: __t.f32().name("fire_resistance"),
});
