// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.uuid(),
  slug: __t.string(),
  widthPx: __t.u32().name("width_px"),
  heightPx: __t.u32().name("height_px"),
  contentHash: __t.string().name("content_hash"),
  data: __t.byteArray(),
});
