// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  levelId: __t.uuid().name("level_id"),
  z: __t.u8(),
  widthPx: __t.u32().name("width_px"),
  heightPx: __t.u32().name("height_px"),
  parallaxX: __t.f32().name("parallax_x"),
  parallaxY: __t.f32().name("parallax_y"),
  encoding: __t.string(),
  contentHash: __t.string().name("content_hash"),
  data: __t.byteArray(),
});
