// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  levelId: __t.uuid().name("level_id"),
  componentId: __t.uuid().name("component_id"),
  get position() {
    return Vec3;
  },
  flipX: __t.bool().name("flip_x"),
  scale: __t.f32(),
  order: __t.u32(),
});
