// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec2,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  slug: __t.string(),
  name: __t.string(),
  get spawn() {
    return Vec2;
  },
  get finish() {
    return Vec2;
  },
});
